description: "Ancestry check by comparing the sample vcf with a 1kgp reference vcf"
keywords:
  - prs
  - ancestry
components:
  - bcftools/merge:
      git_remote: https://github.com/nf-core/modules.git
  - bcftools/view:
      git_remote: https://github.com/nf-core/modules.git
  - plink2/pca:
      git_remote: https://github.com/nf-core/modules.git
  - plink2/indeppairwise:
      git_remote: https://github.com/nf-core/modules.git
  - ancestry/calc
  - ancestry/merge
  - plink2/extract
  - plink2/vcfexpanded
