description: "Creation of interval files based on the provided PRS model"
keywords:
  - prs
  - intervals

components:
  - bcftools/sort:
      git_remote: https://github.com/nf-core/modules.git
  - prsutils/snplist
  - prsutils/getvcf
  - pgscatalog/combine
