org_path: UMCUGenetics
repository_type: modules
lint:
  main_nf:
    - when_exist
  meta_yml: false
  environment_yml: False
  module_changes: False
  module_deprecations: False
  module_version: False
  module_patch: False
