name: "testmodule_testprocess"
description: Extract SNP list from a scoring file
keywords:
  - snp
  - scoring
tools:
  - custom:
      description: Custom SNP list extraction script
      homepage: https://github.com/UMCUGenetics/Modules
input:
  - - meta:
        type: map
        description: Groovy map with sample metadata (e.g. id)
    - scoring_file:
        type: file
        description: Scoring file to extract SNPs from
output:
  - list:
      - meta:
          type: map
          description: Groovy map with sample metadata
      - "*_snplist.list":
          type: file
          description: SNP list file
