name: "prepare_ica_references"
description: "Prepare ica genome reference tar into fasta, fai, dict channels"
keywords:
  - prs
components:
  - untar:
      git_remote: https://github.com/nf-core/modules.git
  - samtools/faidx:
      git_remote: https://github.com/nf-core/modules.git
  - gatk4/createsequencedictionary:
      git_remote: https://github.com/nf-core/modules.git
